//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpAssistantGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpAssistantGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link xlink:href=&quot;{0:c}#{1:c}&quot;/&gt;.
        /// </summary>
        internal static string anchorLinkString {
            get {
                return ResourceManager.GetString("anchorLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;codeEntityReference&gt;{0:c}&lt;/codeEntityReference&gt;.
        /// </summary>
        internal static string codeEntityLinkString {
            get {
                return ResourceManager.GetString("codeEntityLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;codeEntityReference&gt;
        ///    {0:c}
        ///&lt;/codeEntityReference&gt;.
        /// </summary>
        internal static string codeEntityLinkStringFormatted {
            get {
                return ResourceManager.GetString("codeEntityLinkStringFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;externalLink&gt;&lt;linkText&gt;{0:c}&lt;/linkText&gt;&lt;linkAlternateText&gt;{1:c}&lt;/linkAlternateText&gt;&lt;linkUri&gt;{2:c}&lt;/linkUri&gt;&lt;/externalLink&gt;.
        /// </summary>
        internal static string externalLinkString {
            get {
                return ResourceManager.GetString("externalLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;externalLink&gt;
        ///  &lt;linkText&gt;{0:c}&lt;/linkText&gt;
        ///  &lt;linkAlternateText&gt;{1:c}&lt;/linkAlternateText&gt;
        ///  &lt;linkUri&gt;{2:c}&lt;/linkUri&gt;
        ///&lt;/externalLink&gt;.
        /// </summary>
        internal static string externalLinkStringFormatted {
            get {
                return ResourceManager.GetString("externalLinkStringFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;mediaLink&gt;&lt;caption placement=&quot;after&quot; lead=&quot;Figure&quot;&gt;{0:c}&lt;/caption&gt;&lt;image placement=&quot;center&quot; xlink:href = &quot;{1:c}&quot;/&gt;&lt;/mediaLink&gt;.
        /// </summary>
        internal static string imageLinkString {
            get {
                return ResourceManager.GetString("imageLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;mediaLink&gt;
        ///    &lt;caption placement=&quot;after&quot; lead=&quot;Figure&quot;&gt;{0:c}&lt;/caption&gt;
        ///    &lt;image placement=&quot;center&quot; xlink:href = &quot;{1:c}&quot;/&gt;
        ///&lt;/mediaLink&gt;.
        /// </summary>
        internal static string imageLinkStringFormatted {
            get {
                return ResourceManager.GetString("imageLinkStringFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;token&gt;{0:c}&lt;/token&gt;.
        /// </summary>
        internal static string tokenLinkString {
            get {
                return ResourceManager.GetString("tokenLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;token&gt;
        ///    {0:c}
        ///&lt;/token&gt;.
        /// </summary>
        internal static string tokenLinkStringFormatted {
            get {
                return ResourceManager.GetString("tokenLinkStringFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link xlink:href=&quot;{0:c}&quot;/&gt;.
        /// </summary>
        internal static string topicLinkString {
            get {
                return ResourceManager.GetString("topicLinkString", resourceCulture);
            }
        }
    }
}
