//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.3053
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace CAS.MAML.HelpTopics.Content
{
  /// <uwagi/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.42" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://cas.eu/2009/HelpContent.xsd" )]
  [System.Xml.Serialization.XmlRootAttribute( Namespace = "http://cas.eu/2009/HelpContent.xsd", IsNullable = false )]
  public partial class Topics
  {

    private TopicNode[] topicNodeField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute( "TopicNode" )]
    public TopicNode[] TopicNode
    {
      get
      {
        return this.topicNodeField;
      }
      set
      {
        this.topicNodeField = value;
      }
    }
  }

  /// <uwagi/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd", "2.0.50727.42" )]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute( "code" )]
  [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://cas.eu/2009/HelpContent.xsd" )]
  public partial class TopicNode
  {

    private string urlField;

    private string titleField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Url
    {
      get
      {
        return this.urlField;
      }
      set
      {
        this.urlField = value;
      }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title
    {
      get
      {
        return this.titleField;
      }
      set
      {
        this.titleField = value;
      }
    }
  }
}
